### ISSUE TITLE
Настроить dev-окружение для windows

### ISSUE THREAD

**Issue by vehsamrak** [MagicGreenHat/Kingdom#85]
С помощью vagrant сделать образ с докером, способный загружать окружение.
Решить проблему с shared folders в виртуалбоксе

**Comment by samizdam** [comment]
+1 =)

**Comment by vehsamrak** [comment]
@samizdam я настроил вагрант, поднял докер. И оказалось что новая версия докера имеет непофикшенный баг препятствующий работе этой связки. Пробовал недели три назад, докер с тех пор мог обновиться, надо посмотреть еще раз

**Comment by Nosolok** [comment]
Второй!

**Comment by vehsamrak** [comment]
@Nosolok @samizdam 
Если установить расширение для хрома https://www.zenhub.io
то появится возможность ставить +1 комментариям.
Так же в задачах появится канбан доска:
![2015-12-22 23 55 59](https://cloud.githubusercontent.com/assets/4052919/11965717/93ded7dc-a907-11e5-9720-7b4f13e28a4e.png)

**Comment by vehsamrak** [comment]
@samizdam @Nosolok 
Вагрант сконфигурирован, попробуйте.

Описание из README.md:
Установка под Windows (версия для разработки)

1.Установить Vagrant: https://www.vagrantup.com/downloads.html
2.vagrant plugin install vagrant-triggers
3.Из директории проекта выполнить vagrant up
- Для загрузки необходимо время.

4.После загрузки игра будет доступна на 8000 порту (http://localhost:8000)
5.Серверная консоль доступна внутри виртуальной машины, подключиться к которой можно командой vagrant ssh. Затем, внутри виртуальной машины нужно переместиться в директорию с игрой cd /kingdom где затем можно вызвать консоль ./kingdom.sh
6.Если сервер не может подключиться к базе данных, необходимо выполнить внутри виртуальной машины команду /kingdom/kingdom.sh drop-database и заново перезапустить образ.

**Comment by samizdam** [comment]
Такс, я попробовал запустить это дело. 
Из шторма, запуск сказал, что не может использовать текущий порт. С настройками   
config.vm.network "forwarded_port", guest: 80, host: 80
я получил
`
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 80 is already in use
on the host machine.

To fix this, modify your current project's Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 80, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.

Process finished with exit code 1
`
Тогда я поменял порт на 1234 и воспользовался git bash, т.к. мой терминал в шторме не обучен работе с ssh. После успешно запуска, при выполнении kingdom.sh я получил сообщение о недостатке памяти: 

`
$ vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Apr 22 21:06:18 UTC 2016

  System load:  0.74              Processes:              81
  Usage of /:   4.7% of 39.34GB   Users logged in:        0
  Memory usage: 56%               IP address for eth0:    10.0.2.15
  Swap usage:   0%                IP address for docker0: 172.17.0.1

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud


vagrant@vagrant-ubuntu-trusty-64:~$ ls
vagrant@vagrant-ubuntu-trusty-64:~$ cd /kingdom/
vagrant@vagrant-ubuntu-trusty-64:/kingdom$ ./kingdom.sh
--------------------------------------------------------------------
./kingdom.sh start [dev|test] - Запуск контейнера [в dev-окружении (без кэширования)]
./kingdom.sh restart [dev|test]- Немедленный перезапуск контейнеров
./kingdom.sh stop - Остановка контейнера
./kingdom.sh reboot [dev] - Отложенная перезагрузка (с оповещением игроков)

./kingdom.sh log [game|players|nginx]- просмотр логов
./kingdom.sh bash - Запуск серверной консоли
./kingdom.sh mysql - Запуск консоли MySQL
./kingdom.sh update - Обновление структуры базы данных
./kingdom.sh console - Консоль Symfony
./kingdom.sh (cache|clear) [warm] - Очистка кэша
./kingdom.sh (css|js|gulp) - Сборка CSS и JS с помощью gulp

./kingdom.sh broadcast (phrase) - Отправка сообщения всем игрокам онлайн

./kingdom.sh deploy (dev) - Деплой проекта (git pull, рестарт серверов)
./kingdom.sh test (d|v|-d|-v|debug)- Запуск автоматических тестов (с выводом)
./kingdom.sh build - Сборка нового Docker-образа
./kingdom.sh drop-database - Удаление всех данных из БД
./kingdom.sh check [update [package_name|--all]] - Проверка новых пакетов composer (vinkla/climb)
----------------------------------------------------------------------
vagrant@vagrant-ubuntu-trusty-64:/kingdom$ ./kingdom.sh start
Удаление старого контейнера ...
Контейнер остановлен и удален!
Обновление образа из Docker hub ...
php7: Pulling from rottenwood/kingdom
9943fffae777: Pull complete
fb15e825cb68: Pull complete
b9583a207297: Pull complete
a3ed95caeb02: Pull complete
50ea9638159e: Pull complete
39c5960d2ba0: Pull complete
790459373875: Pull complete
64145489f417: Pull complete
92e6489d5b2a: Pull complete
a29e8abb38be: Pull complete
Digest: sha256:0d298397ca32abec00ec053dd68841b25499db32322e5d0aa2acb74466007784
Status: Downloaded newer image for rottenwood/kingdom:php7
Настройка контейнера данных для MySQL ...
cat: app/config/parameters.yml: No such file or directory
cat: app/config/parameters.yml: No such file or directory
\033[1;31mКонфиг app/config/parameters.yml не найден! Запуск composer install ...\033[0m
--2016-04-22 21:15:32--  https://getcomposer.org/composer.phar
Resolving getcomposer.org (getcomposer.org)... 87.98.253.108, 2001:41d0:a:7b19::2
Connecting to getcomposer.org (getcomposer.org)|87.98.253.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1625160 (1.5M) [application/octet-stream]
Saving to: ‘composer.phar’

100%[====================================================>] 1,625,160   1.40MB/s   in 1.1s

2016-04-22 21:15:34 (1.40 MB/s) - ‘composer.phar’ saved [1625160/1625160]

/usr/bin/env: php: No such file or directory
Запуск контейнера с сервером MySQL ...
cat: app/config/parameters.yml: No such file or directory
cat: app/config/parameters.yml: No such file or directory
Unable to find image 'tutum/mysql:latest' locally
latest: Pulling from tutum/mysql
faecf96fd5ab: Pull complete
995977506e98: Pull complete
efb63fb8dcb6: Pull complete
a3ed95caeb02: Pull complete
9bd85a352aaf: Pull complete
04b9dc962d33: Pull complete
4b9893af6e25: Pull complete
ccf4d560b7b4: Pull complete
f4604a58b411: Pull complete
Digest: sha256:829b7a518d16fc224b698492b734298d6f05bcec868ecbed49b4ae8fc135c524
Status: Downloaded newer image for tutum/mysql:latest
d5e2d67ca8aff06e786c7f1d52694c17eebce6226ebb700a400ccc0c48e73c52
docker: Error response from daemon: driver failed programming external connectivity on endpoint kingdom-mysql-server (2f44d0488038819ab79b897c531ba53d288401cbf3a6995039afb9e10e5de256): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 3307 -j DNAT --to-destination 172.17.0.2:3306 ! -i docker0:  (fork/exec /sbin/iptables: cannot allocate memory).
Выбрано symfony окружение: prod
Создание нового контейнера ...
caf2e6ff27ea1f48bc9dad5dbdc5ae1c497ed7926ac04064e838a0a76f26cc6f
docker: Error response from daemon: driver failed programming external connectivity on endpoint kingdom (0d88aec31752fc0db3c075e0e78720b07bce3c0b1f5baab65801aebd0c8a861c): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 81 -j DNAT --to-destination 172.17.0.2:81 ! -i docker0:  (fork/exec /sbin/iptables: cannot allocate memory).
Контейнер не был создан!
vagrant@vagrant-ubuntu-trusty-64:/kingdom$ exit
logout
Connection to 127.0.0.1 closed.

`
Я увеличил это значение в Vagrantfile до 512 и, похоже успешно запустил программу: 
`
$ vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Apr 22 21:37:42 UTC 2016

  System load:  0.6               Processes:              83
  Usage of /:   7.5% of 39.34GB   Users logged in:        0
  Memory usage: 27%               IP address for eth0:    10.0.2.15
  Swap usage:   0%                IP address for docker0: 172.17.0.1

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud


Last login: Fri Apr 22 21:28:17 2016 from 10.0.2.2
vagrant@vagrant-ubuntu-trusty-64:~$ cd /kingdom/
vagrant@vagrant-ubuntu-trusty-64:/kingdom$ ./kingdom.sh start
Удаление старого контейнера ...
Контейнер остановлен и удален!
Обновление образа из Docker hub ...
php7: Pulling from rottenwood/kingdom
9943fffae777: Already exists
fb15e825cb68: Already exists
b9583a207297: Already exists
a3ed95caeb02: Already exists
50ea9638159e: Already exists
39c5960d2ba0: Already exists
790459373875: Already exists
64145489f417: Already exists
92e6489d5b2a: Already exists
a29e8abb38be: Already exists
Digest: sha256:0d298397ca32abec00ec053dd68841b25499db32322e5d0aa2acb74466007784
Status: Image is up to date for rottenwood/kingdom:php7
Настройка контейнера данных для MySQL ...
cat: app/config/parameters.yml: No such file or directory
cat: app/config/parameters.yml: No such file or directory
\033[1;31mКонфиг app/config/parameters.yml не найден! Запуск composer install ...\033[0m
--2016-04-22 21:38:06--  https://getcomposer.org/composer.phar
Resolving getcomposer.org (getcomposer.org)... 87.98.253.108, 2001:41d0:a:7b19::2
Connecting to getcomposer.org (getcomposer.org)|87.98.253.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1625160 (1.5M) [application/octet-stream]
Saving to: ‘composer.phar.2’

100%[====================================================>] 1,625,160   1.50MB/s   in 1.0s

2016-04-22 21:38:08 (1.50 MB/s) - ‘composer.phar.2’ saved [1625160/1625160]

/usr/bin/env: php: No such file or directory
Запуск контейнера с сервером MySQL ...
cat: app/config/parameters.yml: No such file or directory
cat: app/config/parameters.yml: No such file or directory
4f7b3bb63482655d2e416d79e909ec3ac4779e9dcaaf321bf1262d880cc7103d
Выбрано symfony окружение: prod
Создание нового контейнера ...
edb8c1c442fe893f17ceacead7614a51886f06a053d65065d57c565506bb9c01
Контейнер создан!
Игра доступна по адресу: http://172.17.0.1:81
Если контейнер запускается впервые, системе понадобится время для установки и настройки.
Это может занять около минуты. Детальная информация в логах: ./kingdom.sh log
vagrant@vagrant-ubuntu-trusty-64:/kingdom$

`

Внимание, вопрос:** по какому адресу в хост машине, я могу открыть игру**? Ни один из упоминаемых портов и ip не привёл к успеху!

**Comment by samizdam** [comment]
Оп, прошу прощения, забыл обновиться из апстрима. Похоже, всё поменялось.

**Comment by samizdam** [comment]
Имею следующую проблему:

`
$ vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  
  System information as of Sat Apr 23 22:33:18 UTC 2016
  
  System load:  0.46              Processes:              81
  Usage of /:   7.6% of 39.34GB   Users logged in:        0
  Memory usage: 27%               IP address for eth0:    10.0.2.15
  Swap usage:   0%                IP address for docker0: 172.17.0.1
  
  Graph this data and manage this system at:
    https://landscape.canonical.com/
  
  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

Last login: Sat Apr 23 22:31:49 2016 from 10.0.2.2
vagrant@vagrant-ubuntu-trusty-64:~$ cd /kingdom/
vagrant@vagrant-ubuntu-trusty-64:/kingdom$ ./kingdom.sh start
Удаление старого контейнера ...
Контейнер остановлен и удален!
Обновление образа из Docker hub ...
php7: Pulling from rottenwood/kingdom
9943fffae777: Already exists
fb15e825cb68: Already exists
b9583a207297: Already exists
a3ed95caeb02: Already exists
50ea9638159e: Already exists
39c5960d2ba0: Already exists
790459373875: Already exists
64145489f417: Already exists
92e6489d5b2a: Already exists
a29e8abb38be: Already exists
Digest: sha256:0d298397ca32abec00ec053dd68841b25499db32322e5d0aa2acb74466007784
Status: Image is up to date for rottenwood/kingdom:php7
Настройка контейнера данных для MySQL ...
cat: app/config/parameters.yml: No such file or directory
cat: app/config/parameters.yml: No such file or directory
Конфиг app/config/parameters.yml не найден! Установка дефолтных паролей для БД
Запуск контейнера с сервером MySQL ...
bbcf8e873dc5727a69695cdf8e5692473f781a116653085d3931c837d3cb7523
Выбрано symfony окружение: prod
Создание нового контейнера ...
516feb2b0f95080ac2254d3c3ebb11467993f8e05c16915e9261cb129b3d3256
docker: Error response from daemon: Container command 'kingdom/app/docker/init.sh' not found or does not exist..
Контейнер не был создан!
`

**Comment by vehsamrak** [comment]
> vagrant@vagrant-ubuntu-trusty-64:/kingdom$ ./kingdom.sh start
> нужно ./kingdom.sh start dev

Но вообще нет необходимости это делать вручную. **vagrant up** из корня проекта сам все сделает и поднимет

**Comment by samizdam** [comment]
Да, удалось всё поднять! 
Спасибо.
